param(
  [int]$Port = 5173,
  [switch]$NoOpen,
  [switch]$NoInstall,
  [switch]$UseSupabase,
  [switch]$CheckOnly
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Write-Step($Message) {
  Write-Host "[Balloon Burst Gift] $Message" -ForegroundColor Cyan
}

function Test-PortAvailable([int]$CandidatePort) {
  $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Parse("127.0.0.1"), $CandidatePort)
  try {
    $listener.Start()
    return $true
  } catch {
    return $false
  } finally {
    $listener.Stop()
  }
}

function Find-AvailablePort([int]$PreferredPort) {
  for ($candidate = $PreferredPort; $candidate -lt ($PreferredPort + 50); $candidate++) {
    if (Test-PortAvailable $candidate) {
      return $candidate
    }
  }

  throw "No available port found from $PreferredPort to $($PreferredPort + 49)."
}

function Ensure-EnvFile([string]$ProjectRoot, [bool]$SupabaseMode) {
  $envPath = Join-Path $ProjectRoot ".env.local"
  $mode = if ($SupabaseMode) { "supabase" } else { "memory" }

  if (-not (Test-Path -LiteralPath $envPath)) {
    @(
      "# Auto-generated by scripts/start-dev.ps1"
      "VITE_REPOSITORY_MODE=$mode"
      "VITE_SUPABASE_URL=https://your-project.supabase.co"
      "VITE_SUPABASE_ANON_KEY=your-anon-key"
    ) | Set-Content -LiteralPath $envPath -Encoding UTF8
    Write-Step "Created .env.local with VITE_REPOSITORY_MODE=$mode."
    return
  }

  $envText = Get-Content -LiteralPath $envPath -Raw
  if ($envText -notmatch "(?m)^VITE_REPOSITORY_MODE=") {
    Add-Content -LiteralPath $envPath -Value "`nVITE_REPOSITORY_MODE=$mode"
    Write-Step "Added VITE_REPOSITORY_MODE=$mode to .env.local."
  } else {
    Write-Step ".env.local already exists; keeping its repository mode."
  }
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptRoot
Set-Location -LiteralPath $projectRoot

Write-Step "Project root: $projectRoot"
Ensure-EnvFile $projectRoot ([bool]$UseSupabase)

$toolsPath = Join-Path $projectRoot "tools"
if (Test-Path -LiteralPath $toolsPath) {
  $env:PATH = "$toolsPath;$env:PATH"
}

$npmCmd = Join-Path $toolsPath "npm.cmd"
if (-not (Test-Path -LiteralPath $npmCmd)) {
  $npmCommand = Get-Command npm -ErrorAction SilentlyContinue
  if (-not $npmCommand) {
    throw "Cannot find npm. Install Node.js or restore tools/npm.cmd."
  }
  $npmCmd = $npmCommand.Source
}

if (-not $NoInstall -and -not (Test-Path -LiteralPath (Join-Path $projectRoot "node_modules"))) {
  Write-Step "Installing dependencies..."
  & $npmCmd install
}

$selectedPort = Find-AvailablePort $Port
$localUrl = "http://127.0.0.1:$selectedPort/"
$localhostUrl = "http://localhost:$selectedPort/"

Write-Step "Ready. App URL: $localUrl"
Write-Step "Alternative URL: $localhostUrl"

if ($CheckOnly) {
  Write-Step "Check-only mode finished; dev server was not started."
  exit 0
}

if (-not $NoOpen) {
  Start-Job -ScriptBlock {
    param([string]$Url, [int]$ReadyPort)
    for ($attempt = 0; $attempt -lt 60; $attempt++) {
      $client = [System.Net.Sockets.TcpClient]::new()
      try {
        $connected = $client.BeginConnect("127.0.0.1", $ReadyPort, $null, $null)
        if ($connected.AsyncWaitHandle.WaitOne(500)) {
          $client.EndConnect($connected)
          Start-Process $Url
          return
        }
      } catch {
      } finally {
        $client.Close()
      }
      Start-Sleep -Milliseconds 500
    }
  } -ArgumentList $localUrl, $selectedPort | Out-Null
}

Write-Step "Starting Vite. Keep this window open while using the app. Press Ctrl+C to stop."
& $npmCmd run dev -- --host 127.0.0.1 --port $selectedPort --strictPort
